export const requiredFields = [
    { key: 'acc_id', label: 'Vendor' },
    { key: 'site_cat_id', label: 'Site Category' },
    { key: 'country_id', label: 'Country' },
    { key: 'state_id', label: 'State' },
    { key: 'city_id', label: 'City' },
    { key: 'm_f_id', label: 'Media Format' },
    { key: 'm_v_id', label: 'Media Vehicle' },
    { key: 'm_t_id', label: 'Media Type' },
    { key: 's_s_id', label: 'Site Status' },
    { key: 'rating_id', label: 'Rating' },
    { key: 'a_s_id', label: 'Availability Status' },
    { key: 'location', label: 'Location' },
    { key: 'traffic_from', label: 'Traffic From' },
    { key: 'traffic_to', label: 'Traffic To' },
    { key: 'position_of_site', label: 'Position of Site' },
    { key: 'lat_long', label: 'Latitude Longitude' },
    { key: 'p_night_shot', label: 'Night Shot' },
    { key: 'p_long_shot', label: 'Long Shot' },
    { key: 'p_close_shot', label: 'Close Shot' },
    { key: 'card_rate', label: 'Card Rate/Month' },
    { key: 'leased_cost', label: 'Leased Cost/Month' },
    { key: 'buying_cost', label: 'Buying Cost/Month' },
    { key: 'selling_cost', label: 'Selling Cost/Month' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'width', label: 'Width' },
    { key: 'height', label: 'Height' },
    { key: 'remarks', label: 'Remark' },
  ];


  export const leaseFields = [
    { key: 'available_from', label: 'Available From' },
    { key: 'available_to', label: 'Available To' },
    { key: 'lease_from', label: 'Lease From' },
    { key: 'lease_to', label: 'Lease To' },
    { key: 'lease_period', label: 'Lease Period' },
    { key: 'lease_cost', label: 'Lease Cost' },
  ];